server:
  port: 8080
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka 

spring:
  cloud:
    gateway:
      routes:
      - id: clientModule
        uri: lb://CLIENT-SERVICE
        predicates:
        - Path=/clients/**